title: modulith
description: Modulith is a dotnet new template for Modular Monoliths. It streamlines the creation of new .Net solutions and the addition of modules to existing ones.
theme: just-the-docs
plugins:
  - jekyll-feed

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/salzaki/modulith
